### PR TITLE
Add the missing colon

### PR DESCRIPTION
**Pull request by haibin**

### CODE REVIEW

**Comment by hjwp** [comment]
brilliant, thanks.

how are you enjoying the book?  we'd love to hear any and all feedback, in any form...

**Comment by haibin** [comment]
It's really good. enjoy it very much. i'm still reading through the 1st part and will go feedback along the way.

**Comment by hjwp** [comment]
that would be _amazing_.  feel free to submit feedback using a github pull request with comments directly in the source if you like.  or you can open issues.  or email us via python-leap@gmail.com.  whatever is easiest for you!

**Comment by Chris-May** [comment]
FWIW, the python-leap@gmail.com email address bounced.
`<python-leap@gmail.com>: host gmail-smtp-in.l.google.com[172.217.197.26] said:
    550-5.1.1 The email account that you tried to reach does not exist. Please
    try 550-5.1.1 double-checking the recipient's email address for typos or
    550-5.1.1 unnecessary spaces.`

**Comment by hjwp** [comment]
ah it should be pythonleap@gmail.com

**Pull request merged**
