### PR TITLE
reference fix.

### PR DESCRIPTION
**Pull request by clintonroy**

### CODE REVIEW

**Comment by hjwp** [comment]
thanks again!

**Comment by hjwp** [comment]
for info: https://github.com/python-leap/book/commit/4f5de00acfd5ccf85be40597291e86f3899cac58

**Comment by hjwp** [comment]
in general, how are you enjoying the book so far?

**Comment by clintonroy** [comment]
I am liking the content so far, I'm struggling to work out if I can apply it at work (we're not a particularly large group, but we are making a large system). I'm really no good at giving large editorial comments, only small fixes.

**Comment by hjwp** [comment]
re: editorial feedback, not to worry, small fixes are always welcome. if you do ever come across a passage that's particularly unclear or confusing though, please do give us a shout.

re: working out how to apply it irl, we're planning a chapter at the end along the lines of "how do i get there from here".  would be very interested to hear what practical difficulties you foresee - is it around convincing others, figuring out if it's all worth it, choosing which patterns to use and which not, or is it more around how to migrate an existing codebase?

**Pull request merged**
